name: vphone-aio-ngrok

on:
  workflow_dispatch:

jobs:
  vphone:
    runs-on: macos-latest
    timeout-minutes: 360

    steps:

      # Clone repo
      - uses: actions/checkout@v4

      # Install prerequisites
      - name: Install deps
        run: |
          brew update
          brew install git-lfs wget zstd libimobiledevice

      # Install ngrok
      - name: Install ngrok
        run: |
          brew install ngrok/ngrok/ngrok

      # Add ngrok auth token
      - name: Setup ngrok auth
        run: |
          ngrok config add-authtoken 2nyiyWrhpT6OwyUoaoZ2zdE9nNo_7KtHBQxaox3Wx2t9qBHTT

      # Download parts (README step)
      - name: Download split archive
        run: |
          for p in aa ab ac ad ae af ag; do
            wget -O "vphone-cli.tar.zst.part_${p}" \
            "https://github.com/34306/vphone-aio/raw/refs/heads/main/vphone-cli.tar.zst.part_${p}?download="
          done

      # Merge
      - name: Merge archive
        run: |
          cat vphone-cli.tar.zst.part_* > vphone-cli.tar.zst

      # Extract
      - name: Extract
        run: |
          zstd -dc vphone-cli.tar.zst | tar xf -

      # Cleanup
      - name: Cleanup
        run: |
          rm -rf .git
          rm -f vphone-cli.tar.zst*
      
      # Make executable
      - name: Permission
        run: chmod +x vphone-aio.sh

      # Start vPhone
      - name: Run vPhone
        run: |
          ./vphone-aio.sh &
          sleep 60

      # Open VNC tunnel
      - name: Start ngrok TCP tunnel
        run: |
          ngrok tcp 5901 > ngrok.log &
          sleep 10
          cat ngrok.log

      # Keep runner alive
      - name: Keep alive
        run: |
          while true; do
            echo "vPhone running..."
            sleep 60
          done
